/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jtilib;

/**
 *
 * @author choirulhuda
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RootPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        WelcomeLabel = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        BorrowButton = new javax.swing.JButton();
        BookButton = new javax.swing.JButton();
        LateButton = new javax.swing.JButton();
        AboutButton = new javax.swing.JButton();
        CreditLabel = new javax.swing.JLabel();
        CopyRightLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EditorPanel = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        HomeEditorLabel = new javax.swing.JLabel();
        BorrowPanel = new javax.swing.JPanel();
        BorrowEditorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(72, 219, 251));
        setPreferredSize(new java.awt.Dimension(750, 530));
        setResizable(false);

        RootPanel.setBackground(new java.awt.Color(200, 214, 229));
        RootPanel.setPreferredSize(new java.awt.Dimension(750, 530));

        MenuPanel.setBackground(new java.awt.Color(87, 101, 116));

        WelcomeLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        WelcomeLabel.setForeground(new java.awt.Color(255, 255, 255));
        WelcomeLabel.setText("Welcome");

        HomeButton.setBackground(new java.awt.Color(87, 101, 116));
        HomeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HomeButton.setIcon(new javax.swing.ImageIcon("E:\\Mengajar\\Mata Kuliah\\Pemrograman Berbasis Desktop\\Proyek\\JTILib\\icon\\ic_home_white.png")); // NOI18N
        HomeButton.setText("Home");
        HomeButton.setToolTipText("");
        HomeButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        HomeButton.setIconTextGap(10);
        HomeButton.setMargin(new java.awt.Insets(2, 10, 2, 14));
        HomeButton.setNextFocusableComponent(this);
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });

        BorrowButton.setBackground(new java.awt.Color(87, 101, 116));
        BorrowButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BorrowButton.setIcon(new javax.swing.ImageIcon("E:\\Mengajar\\Mata Kuliah\\Pemrograman Berbasis Desktop\\Proyek\\JTILib\\icon\\ic_handel_book_white.png")); // NOI18N
        BorrowButton.setText("Borrow");
        BorrowButton.setToolTipText("");
        BorrowButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BorrowButton.setIconTextGap(10);
        BorrowButton.setMargin(new java.awt.Insets(2, 12, 2, 14));
        BorrowButton.setNextFocusableComponent(this);
        BorrowButton.setOpaque(false);
        BorrowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrowButtonActionPerformed(evt);
            }
        });

        BookButton.setBackground(new java.awt.Color(87, 101, 116));
        BookButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BookButton.setIcon(new javax.swing.ImageIcon("E:\\Mengajar\\Mata Kuliah\\Pemrograman Berbasis Desktop\\Proyek\\JTILib\\icon\\ic_book_white.png")); // NOI18N
        BookButton.setText("Books");
        BookButton.setToolTipText("");
        BookButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BookButton.setIconTextGap(14);
        BookButton.setMargin(new java.awt.Insets(2, 12, 2, 14));
        BookButton.setNextFocusableComponent(this);
        BookButton.setOpaque(false);
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });

        LateButton.setBackground(new java.awt.Color(87, 101, 116));
        LateButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LateButton.setIcon(new javax.swing.ImageIcon("E:\\Mengajar\\Mata Kuliah\\Pemrograman Berbasis Desktop\\Proyek\\JTILib\\icon\\ic_late_white.png")); // NOI18N
        LateButton.setText("Late");
        LateButton.setToolTipText("");
        LateButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LateButton.setIconTextGap(12);
        LateButton.setMargin(new java.awt.Insets(2, 10, 2, 14));
        LateButton.setNextFocusableComponent(this);
        LateButton.setOpaque(false);
        LateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LateButtonActionPerformed(evt);
            }
        });

        AboutButton.setBackground(new java.awt.Color(87, 101, 116));
        AboutButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AboutButton.setIcon(new javax.swing.ImageIcon("E:\\Mengajar\\Mata Kuliah\\Pemrograman Berbasis Desktop\\Proyek\\JTILib\\icon\\ic_about_white.png")); // NOI18N
        AboutButton.setText("About");
        AboutButton.setToolTipText("");
        AboutButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        AboutButton.setIconTextGap(12);
        AboutButton.setMargin(new java.awt.Insets(2, 10, 2, 14));
        AboutButton.setNextFocusableComponent(this);
        AboutButton.setOpaque(false);
        AboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutButtonActionPerformed(evt);
            }
        });

        CreditLabel.setBackground(new java.awt.Color(255, 255, 255));
        CreditLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        CreditLabel.setForeground(new java.awt.Color(255, 255, 255));
        CreditLabel.setText("CREDITS");

        CopyRightLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CopyRightLabel.setForeground(new java.awt.Color(255, 255, 255));
        CopyRightLabel.setText("All copyrights @ Creative App");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JTI Library App");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(CopyRightLabel))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(CreditLabel))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WelcomeLabel)
                            .addComponent(jLabel2)))
                    .addGroup(MenuPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BorrowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(HomeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(WelcomeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(HomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BorrowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CreditLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CopyRightLabel)
                .addGap(67, 67, 67))
        );

        EditorPanel.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(131, 149, 167));

        HomeEditorLabel.setBackground(new java.awt.Color(131, 149, 167));
        HomeEditorLabel.setForeground(new java.awt.Color(255, 255, 255));
        HomeEditorLabel.setText("Menu Home");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeEditorLabel)
                .addContainerGap(458, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HomeEditorLabel)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        EditorPanel.add(HomePanel, "card2");

        BorrowPanel.setBackground(new java.awt.Color(200, 214, 229));

        BorrowEditorLabel.setText("Menu Borrow");

        javax.swing.GroupLayout BorrowPanelLayout = new javax.swing.GroupLayout(BorrowPanel);
        BorrowPanel.setLayout(BorrowPanelLayout);
        BorrowPanelLayout.setHorizontalGroup(
            BorrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BorrowEditorLabel)
                .addContainerGap(451, Short.MAX_VALUE))
        );
        BorrowPanelLayout.setVerticalGroup(
            BorrowPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BorrowPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BorrowEditorLabel)
                .addContainerGap(505, Short.MAX_VALUE))
        );

        EditorPanel.add(BorrowPanel, "card3");

        javax.swing.GroupLayout RootPanelLayout = new javax.swing.GroupLayout(RootPanel);
        RootPanel.setLayout(RootPanelLayout);
        RootPanelLayout.setHorizontalGroup(
            RootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RootPanelLayout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RootPanelLayout.setVerticalGroup(
            RootPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(EditorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(RootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // remove panel
        EditorPanel.removeAll();
        EditorPanel.repaint();
        EditorPanel.revalidate();
        
        //add panel
        EditorPanel.add(HomePanel);
        EditorPanel.repaint();
        EditorPanel.revalidate();
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void BorrowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrowButtonActionPerformed
        // remove panel
        EditorPanel.removeAll();
        EditorPanel.repaint();
        EditorPanel.revalidate();
        
        //add panel
        EditorPanel.add(BorrowPanel);
        EditorPanel.repaint();
        EditorPanel.revalidate();
    }//GEN-LAST:event_BorrowButtonActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BookButtonActionPerformed

    private void LateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LateButtonActionPerformed

    private void AboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AboutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AboutButton;
    private javax.swing.JButton BookButton;
    private javax.swing.JButton BorrowButton;
    private javax.swing.JLabel BorrowEditorLabel;
    private javax.swing.JPanel BorrowPanel;
    private javax.swing.JLabel CopyRightLabel;
    private javax.swing.JLabel CreditLabel;
    private javax.swing.JPanel EditorPanel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel HomeEditorLabel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JButton LateButton;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel RootPanel;
    private javax.swing.JLabel WelcomeLabel;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
